### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by OrangeEye** [fawkesu/otw-helper#1]
I couldn't started helper because of syntax errors, because of the word "function". I deleted this word so that every function looked like this. 

`get_config() {
	while IFS=" " read -r name config;
	do
		if [ "$name" = "$1" ]; then
			echo $config
			break
		fi
	done < $CONF
}`

After these changes was everything fine.

**Comment by fawkesu** [comment]
Oh yes you're right, I was using the wrong syntax. Thanks !
